name: wms
description: "Multi-platform software and information system for accounting and inventory management of finished products based on Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  sqflite: ^2.4.1
  barcode_scan2: ^4.5.0
  lottie: ^3.2.0
  flutter_localization: ^0.3.1
  jwt_decoder: ^2.0.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  intl: ^0.19.0
  pdf: ^3.11.3
  printing: ^5.14.2
  data_table_2: ^2.5.18
  file_picker: ^9.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  launcher_name: ^1.0.2

launcher_name:
  default: "WMS"
  ru: "Склад"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo_splash_animation.json
    - lib/assets/logo.png
    - lib/assets/app_icon.png
    - lib/assets/fonts/Lato-Bold.ttf
    - lib/assets/fonts/Lato-BoldItalic.ttf
    - lib/assets/fonts/Lato-Italic.ttf
    - lib/assets/fonts/Lato-Regular.ttf
